{
 "title": "Machine Resources",
 "tags": [ "windows" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg(rate(windows_cpu_time_total{mode=\"idle\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 - rate(windows_cpu_time_total{mode=\"idle\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(1 - rate(windows_cpu_time_total{mode=\"idle\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(windows_memory_physical_total_bytes - windows_memory_physical_free_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Usage - Incoming",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "irate(windows_net_bytes_received_total[1m]) * 8 / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Usage - Outcoming",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "irate(windows_net_bytes_sent_total[1m]) * 8 / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VRAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "nvidia_smi_memory_used_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU's Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "ohm_cpu_celsius", "legendFormat": "__auto" },
    { "expr": "avg(ohm_cpu_celsius)", "legendFormat": "__auto" },
    { "expr": "max(ohm_cpu_celsius)", "legendFormat": "__auto" },
    {
     "expr": "ohm_cpu_celsius{sensor=~\"CPU Package\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU's Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "ohm_gpunvidia_celsius", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - windows_logical_disk_free_bytes{volume=~\"[A-Z]:\"} / windows_logical_disk_size_bytes{volume=~\"[A-Z]:\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts duration",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Real Time Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 } }
 ]
}