{
 "title": "Machine Resources",
 "tags": [ "linux" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode='idle'}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 - rate(node_cpu_seconds_total{mode=\"idle\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Usage - Incoming",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"enp6s0|eth0|wlan0\"}[1m]) * 8 / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Usage - Outcoming",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"enp6s0|eth0|wlan0\"}[1m]) * 8 / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "VRAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_FB_USED", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU's Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"platform_coretemp_0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{chip=\"platform_coretemp_0\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(node_hwmon_temp_celsius{chip=\"platform_coretemp_0\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU's Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_TEMP", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{fstype!~\"tmpfs|devtmpfs|overlay|squashfs|nfs|vfat\"} / node_filesystem_size_bytes{fstype!~\"tmpfs|devtmpfs|overlay|squashfs|nfs\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts duration",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Real Time Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 } }
 ]
}